/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEqm6rdN4b6Y4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqm6rdN4b6Y4= >>
// ----------- >>
public class Adresse {
    // ----------- << attribute.annotations@AAAAAAGEqnLlh97bQCw= >>
    // ----------- >>
    private int idAdresse;

    // ----------- << attribute.annotations@AAAAAAGEqnQRXN8NCIo= >>
    // ----------- >>
    private String pays;

    // ----------- << attribute.annotations@AAAAAAGEqnQxJ98VkvI= >>
    // ----------- >>
    private String codePost;

    // ----------- << attribute.annotations@AAAAAAGEqnRA498c0yA= >>
    // ----------- >>
    private String voie;

    // ----------- << attribute.annotations@AAAAAAGEqnRp1N8ksPM= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGEqnRsBd8qS9Y= >>
    // ----------- >>
    private int numero;

    // ----------- << attribute.annotations@AAAAAAGEqnRuEd8ww34= >>
    // ----------- >>
    private String mention;

    // ----------- << attribute.annotations@AAAAAAGEqnhH4985YjE= >>
    // ----------- >>
    private String complement;

    private int getIdAdresse() {
        return idAdresse;
    }

    private String getPays() {
        return pays;
    }

    private String getCodePost() {
        return codePost;
    }

    private String getVoie() {
        return voie;
    }

    private String getNom() {
        return nom;
    }

    private int getNumero() {
        return numero;
    }

    private String getMention() {
        return mention;
    }

    private String getComplement() {
        return complement;
    }

    private void setIdAdresse(int idAdresse) {
        this.idAdresse = idAdresse;
    }

    private void setPays(String pays) {
        this.pays = pays;
    }

    private void setCodePost(String codePost) {
        this.codePost = codePost;
    }

    private void setVoie(String voie) {
        this.voie = voie;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setNumero(int numero) {
        this.numero = numero;
    }

    private void setMention(String mention) {
        this.mention = mention;
    }

    private void setComplement(String complement) {
        this.complement = complement;
    }

// ----------- << class.extras@AAAAAAGEqm6rdN4b6Y4= >>
// ----------- >>
}