/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEqm6KOd3HjWk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqm6KOd3HjWk= >>
// ----------- >>
public class Client {
    // ----------- << attribute.annotations@AAAAAAGEqniMR99BMHk= >>
    // ----------- >>
    private int idClient;

    // ----------- << attribute.annotations@AAAAAAGEqnipH99I7/I= >>
    // ----------- >>
    private String nom;

    // ----------- << attribute.annotations@AAAAAAGEqniq/t9OpW4= >>
    // ----------- >>
    private String prenom;

    // ----------- << attribute.annotations@AAAAAAGEqnisud9U49M= >>
    // ----------- >>
    private String numTel;

    // ----------- << attribute.annotations@AAAAAAGEqniujd9axtc= >>
    // ----------- >>
    private String gps;

    // ----------- << attribute.annotations@AAAAAAGEquX0TBRugkQ= >>
    // ----------- >>
    private Adresse adresse;

    private int getIdClient() {
        return idClient;
    }

    private String getNom() {
        return nom;
    }

    private String getPrenom() {
        return prenom;
    }

    private String getNumTel() {
        return numTel;
    }

    private String getGps() {
        return gps;
    }

    private Adresse getAdresse() {
        return adresse;
    }

    private void setIdClient(int idClient) {
        this.idClient = idClient;
    }

    private void setNom(String nom) {
        this.nom = nom;
    }

    private void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    private void setNumTel(String numTel) {
        this.numTel = numTel;
    }

    private void setGps(String gps) {
        this.gps = gps;
    }

    private void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }

// ----------- << class.extras@AAAAAAGEqm6KOd3HjWk= >>
// ----------- >>
}