/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEqm79J95yIcY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqm79J95yIcY= >>
// ----------- >>
public class Commande {
    // ----------- << attribute.annotations@AAAAAAGEqnq+z9++3sk= >>
    // ----------- >>
    private int numCom;

    // ----------- << attribute.annotations@AAAAAAGEqnrB29/E0+k= >>
    // ----------- >>
    private String libelle;

    // ----------- << attribute.annotations@AAAAAAGEqnrDrt/KeeQ= >>
    // ----------- >>
    private int poids;

    // ----------- << attribute.annotations@AAAAAAGEqnrZwd/QZT4= >>
    // ----------- >>
    private String dateCom;

    // ----------- << attribute.annotations@AAAAAAGEqnrcOd/Wjp8= >>
    // ----------- >>
    private int heureDeb;

    // ----------- << attribute.annotations@AAAAAAGEqnrd/t/cY+I= >>
    // ----------- >>
    private int heureFin;

    // ----------- << attribute.annotations@AAAAAAGEquWejBFIVIE= >>
    // ----------- >>
    private Producteur producteur;

    // ----------- << attribute.annotations@AAAAAAGEquXZUxJXrVs= >>
    // ----------- >>
    private Client client;

    private int getNumCom() {
        return numCom;
    }

    private String getLibelle() {
        return libelle;
    }

    private int getPoids() {
        return poids;
    }

    private String getDateCom() {
        return dateCom;
    }

    private int getHeureDeb() {
        return heureDeb;
    }

    private int getHeureFin() {
        return heureFin;
    }

    private Producteur getProducteur() {
        return producteur;
    }

    private Client getClient() {
        return client;
    }

    private void setNumCom(int numCom) {
        this.numCom = numCom;
    }

    private void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    private void setPoids(int poids) {
        this.poids = poids;
    }

    private void setDateCom(String dateCom) {
        this.dateCom = dateCom;
    }

    private void setHeureDeb(int heureDeb) {
        this.heureDeb = heureDeb;
    }

    private void setHeureFin(int heureFin) {
        this.heureFin = heureFin;
    }

    private void setProducteur(Producteur producteur) {
        this.producteur = producteur;
    }

    private void setClient(Client client) {
        this.client = client;
    }

// ----------- << class.extras@AAAAAAGEqm79J95yIcY= >>
// ----------- >>
}