/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEtghwTQAIwF0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEtghwTQAIwF0= >>
// ----------- >>
public class ListeVehicules {
    // ----------- << attribute.annotations@AAAAAAGEtgiPZgGyPcc= >>
    // ----------- >>
    private ArrayList<Vehicule> vehicules;

    // ----------- << method.annotations@AAAAAAGEtgkbpg2UbRQ= >>
    // ----------- >>
    public ListeVehicules() {
    // ----------- << method.body@AAAAAAGEtgkbpg2UbRQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEtgkqXBDjc1U= >>
    // ----------- >>
    public ArrayList<Vehicule> getVehicules() {
    // ----------- << method.body@AAAAAAGEtgkqXBDjc1U= >>
    // ----------- >>
        return vehicules;
    }

    private void setVehicules(ArrayList<Vehicule> vehicules) {
        this.vehicules = vehicules;
    }

    /**
    * @param v
    */

    // ----------- << method.annotations@AAAAAAGEtgksphIhpdA= >>
    // ----------- >>
    public void ajouter(Vehicule v) {
    // ----------- << method.body@AAAAAAGEtgksphIhpdA= >>
    // ----------- >>
    }
    /**
    * @param v
    */

    // ----------- << method.annotations@AAAAAAGEtgkuRBNfWPk= >>
    // ----------- >>
    public void supprimer(Vehicule v) {
    // ----------- << method.body@AAAAAAGEtgkuRBNfWPk= >>
    // ----------- >>
    }
    /**
    * @param v
    */

    // ----------- << method.annotations@AAAAAAGEtjKOq1UfPfk= >>
    // ----------- >>
    public void editer(Vehicule v) {
    // ----------- << method.body@AAAAAAGEtjKOq1UfPfk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEtghwTQAIwF0= >>
// ----------- >>
}
