/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEs1V8SaXoGtQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEs1V8SaXoGtQ= >>
// ----------- >>
public class ListeProducteurs {
    // ----------- << attribute.annotations@AAAAAAGEs1WkQ6qS7Jw= >>
    // ----------- >>
    private ArrayList<Producteur> producteurs;

    // ----------- << method.annotations@AAAAAAGEs4i4FOOTofo= >>
    // ----------- >>
    public void ListeProducteur() {
    // ----------- << method.body@AAAAAAGEs4i4FOOTofo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs6RzzOhxE9c= >>
    // ----------- >>
    public ArrayList<Producteur> getProducteurs() {
    // ----------- << method.body@AAAAAAGEs6RzzOhxE9c= >>
    // ----------- >>
        return producteurs;
    }

    private void setProducteurs(ArrayList<Producteur> producteurs) {
        this.producteurs = producteurs;
    }

    // ----------- << method.annotations@AAAAAAGEs4jmAuRsl8A= >>
    // ----------- >>
    public void ajouter(Producteur p) {
    // ----------- << method.body@AAAAAAGEs4jmAuRsl8A= >>
    // ----------- >>
    }
    /**
    * @param p
    */

    // ----------- << method.annotations@AAAAAAGEs4jn7uTA2K0= >>
    // ----------- >>
    public void supprimer(Producteur p) {
    // ----------- << method.body@AAAAAAGEs4jn7uTA2K0= >>
    // ----------- >>
    }
    /**
    * @param p
    */

    // ----------- << method.annotations@AAAAAAGEs4jqKOUUIOA= >>
    // ----------- >>
    public void editer(Producteur p) {
    // ----------- << method.body@AAAAAAGEs4jqKOUUIOA= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEs1V8SaXoGtQ= >>
// ----------- >>
}
