/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEsyzjsoU1mSk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsyzjsoU1mSk= >>
// ----------- >>
public class ListeCommandes {
    // ----------- << attribute.annotations@AAAAAAGEsy0Jnoo6Lkw= >>
    // ----------- >>
    private ArrayList<Commande> commandes;

    private void setCommandes(ArrayList<Commande> commandes) {
        this.commandes = commandes;
    }

    // ----------- << method.annotations@AAAAAAGEs3i+00bWeN8= >>
    // ----------- >>
    public ListeCommandes() {
    // ----------- << method.body@AAAAAAGEs3i+00bWeN8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs6PbaeOn+3s= >>
    // ----------- >>
    public ArrayList<Commande> getCommandes() {
    // ----------- << method.body@AAAAAAGEs6PbaeOn+3s= >>
    // ----------- >>
        return commandes;
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEs3byqjqj/Is= >>
    // ----------- >>
    public void ajouter(Commande c) {
    // ----------- << method.body@AAAAAAGEs3byqjqj/Is= >>
    // ----------- >>
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEs3c5KjuWrTk= >>
    // ----------- >>
    public void supprimer(Commande c) {
    // ----------- << method.body@AAAAAAGEs3c5KjuWrTk= >>
    // ----------- >>
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEs3c64Dvqr3M= >>
    // ----------- >>
    public void editer(Commande c) {
    // ----------- << method.body@AAAAAAGEs3c64Dvqr3M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEsyzjsoU1mSk= >>
// ----------- >>
}
