/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEsyzQzoLvOjg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsyzQzoLvOjg= >>
// ----------- >>
public class ListeClients {
    // ----------- << attribute.annotations@AAAAAAGEsy1RI5c9neM= >>
    // ----------- >>
    private ArrayList<Client> clients;

    private void setClients(ArrayList<Client> clients) {
        this.clients = clients;
    }

    // ----------- << method.annotations@AAAAAAGEs3hQa0Oaeew= >>
    // ----------- >>
    public ListeClients() {
    // ----------- << method.body@AAAAAAGEs3hQa0Oaeew= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs6MJ+9zAbHE= >>
    // ----------- >>
    public ArrayList<Client> getClients() {
    // ----------- << method.body@AAAAAAGEs6MJ+9zAbHE= >>
    // ----------- >>
        return clients;
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEs3RT2CvtHh0= >>
    // ----------- >>
    public void ajouter(Client c) {
    // ----------- << method.body@AAAAAAGEs3RT2CvtHh0= >>
    // ----------- >>
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEs3SLiCy8YGk= >>
    // ----------- >>
    public void supprimer(Client c) {
    // ----------- << method.body@AAAAAAGEs3SLiCy8YGk= >>
    // ----------- >>
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEs3S3Wi2L0Pg= >>
    // ----------- >>
    public void editer(Client c) {
    // ----------- << method.body@AAAAAAGEs3S3Wi2L0Pg= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEsyzQzoLvOjg= >>
// ----------- >>
}
