/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGErxaPMtgFzt8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGErxaPMtgFzt8= >>
// ----------- >>
public class ListeTournees {
    // ----------- << attribute.annotations@AAAAAAGErxdRZvxUnlg= >>
    // ----------- >>
    private ArrayList<Tournee> tournees;

    private ArrayList<Tournee> getTournees() {
        return tournees;
    }

    private void setTournees(ArrayList<Tournee> tournees) {
        this.tournees = tournees;
    }

    // ----------- << method.annotations@AAAAAAGEs6IJLNHTkzI= >>
    // ----------- >>
    public ListeTournees() {
    // ----------- << method.body@AAAAAAGEs6IJLNHTkzI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs6JeQNQTpnI= >>
    // ----------- >>
    public ArrayList<Tournee> getTournees() {
    // ----------- << method.body@AAAAAAGEs6JeQNQTpnI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs11f9cEqA50= >>
    // ----------- >>
    public ArrayList<Tournee> getTourneesCourantes() {
    // ----------- << method.body@AAAAAAGEs11f9cEqA50= >>
    // ----------- >>
    }
    /**
    * @param t
    */

    // ----------- << method.annotations@AAAAAAGEs3zSwWZlDjc= >>
    // ----------- >>
    public void ajouter(Tournee t) {
    // ----------- << method.body@AAAAAAGEs3zSwWZlDjc= >>
    // ----------- >>
    }
    /**
    * @param t
    */

    // ----------- << method.annotations@AAAAAAGEs30LyGbvOY8= >>
    // ----------- >>
    public void supprimer(Tournee t) {
    // ----------- << method.body@AAAAAAGEs30LyGbvOY8= >>
    // ----------- >>
    }
    /**
    * @param t
    */

    // ----------- << method.annotations@AAAAAAGEs30N8mccjUo= >>
    // ----------- >>
    public void editer(Tournee t) {
    // ----------- << method.body@AAAAAAGEs30N8mccjUo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGErxaPMtgFzt8= >>
// ----------- >>
}