/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEqm7tpt5Iq/8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqm7tpt5Iq/8= >>
// ----------- >>
public class Tournee {
    // ----------- << attribute.annotations@AAAAAAGEqnvD2N/qTV4= >>
    // ----------- >>
    private int numTournee;

    // ----------- << attribute.annotations@AAAAAAGEqnvHDd/wj5M= >>
    // ----------- >>
    private String libelle;

    // ----------- << attribute.annotations@AAAAAAGEqnvIu9/2bIc= >>
    // ----------- >>
    private int heureMin;

    // ----------- << attribute.annotations@AAAAAAGEqnvKAd/8dUs= >>
    // ----------- >>
    private int heureMax;

    // ----------- << attribute.annotations@AAAAAAGEquYuUBaFwbI= >>
    // ----------- >>
    private Producteur producteur;

    // ----------- << attribute.annotations@AAAAAAGEquaJLhjMFWI= >>
    // ----------- >>
    private Vehicule vehicule;

    // ----------- << attribute.annotations@AAAAAAGEqualxhtbcs4= >>
    // ----------- >>
    private ArrayList<Commande> commandes;

    private int getNumTournee() {
        return numTournee;
    }

    private String getLibelle() {
        return libelle;
    }

    private int getHeureMin() {
        return heureMin;
    }

    private int getHeureMax() {
        return heureMax;
    }

    private Producteur getProducteur() {
        return producteur;
    }

    private Vehicule getVehicule() {
        return vehicule;
    }

    private ArrayList<Commande> getCommandes() {
        return commandes;
    }

    private void setNumTournee(int numTournee) {
        this.numTournee = numTournee;
    }

    private void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    private void setHeureMin(int heureMin) {
        this.heureMin = heureMin;
    }

    private void setHeureMax(int heureMax) {
        this.heureMax = heureMax;
    }

    private void setProducteur(Producteur producteur) {
        this.producteur = producteur;
    }

    private void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }

    private void setCommandes(ArrayList<Commande> commandes) {
        this.commandes = commandes;
    }

    // ----------- << method.annotations@AAAAAAGEqpVftBW/7i4= >>
    // ----------- >>
    public boolean estValide() {
    // ----------- << method.body@AAAAAAGEqpVftBW/7i4= >>
    // ----------- >>
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEq5rnKcQHaFg= >>
    // ----------- >>
    public void ajouteCommande(Commande c) {
    // ----------- << method.body@AAAAAAGEq5rnKcQHaFg= >>
    // ----------- >>
    }
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEq5trncawO9M= >>
    // ----------- >>
    public void retireCommande(Commande c) {
    // ----------- << method.body@AAAAAAGEq5trncawO9M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEqm7tpt5Iq/8= >>
// ----------- >>
}