/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEs0zujFnrcDw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEs0zujFnrcDw= >>
// ----------- >>
public enum TypeUtilisateur {
    Producteur,
    Admin;

// ----------- << enum.extras@AAAAAAGEs0zujFnrcDw= >>
// ----------- >>
}