/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEqm5ksN1zj8g= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqm5ksN1zj8g= >>
// ----------- >>
public class Vehicule {
    // ----------- << attribute.annotations@AAAAAAGEqm/ri96jlIs= >>
    // ----------- >>
    private String immat;

    // ----------- << attribute.annotations@AAAAAAGEqnC+9d6qYDE= >>
    // ----------- >>
    private int poidsMax;

    // ----------- << attribute.annotations@AAAAAAGEquUQlgyoo6w= >>
    // ----------- >>
    private Producteur proprietaire;

    private String getImmat() {
        return immat;
    }

    private int getPoidsMax() {
        return poidsMax;
    }

    private Producteur getProprietaire() {
        return proprietaire;
    }

    private void setImmat(String immat) {
        this.immat = immat;
    }

    private void setPoidsMax(int poidsMax) {
        this.poidsMax = poidsMax;
    }

    private void setProprietaire(Producteur proprietaire) {
        this.proprietaire = proprietaire;
    }

// ----------- << class.extras@AAAAAAGEqm5ksN1zj8g= >>
// ----------- >>
}