/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEw3b2O1CfPvc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEw3b2O1CfPvc= >>
// ----------- >>
public class ClientsFormCtrl {
    // ----------- << method.annotations@AAAAAAGEw3r62FGP3p8= >>
    // ----------- >>
    public void enregistrer() {
    // ----------- << method.body@AAAAAAGEw3r62FGP3p8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw3sGHFGWLWY= >>
    // ----------- >>
    public void cancel() {
    // ----------- << method.body@AAAAAAGEw3sGHFGWLWY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEw3b2O1CfPvc= >>
// ----------- >>
}