/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;


import root.model.ListeClients;
import root.view.ClientsView;
// ----------- << imports@AAAAAAGEqtnSqgaMqNg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqtnSqgaMqNg= >>
// ----------- >>
public class ClientsCtrl {
    // ----------- << attribute.annotations@AAAAAAGEs3UO+TA+yXo= >>
    // ----------- >>
    private ListeClients model;

    // ----------- << attribute.annotations@AAAAAAGEs3KG3yQtq5A= >>
    // ----------- >>
    private ClientsView view;

    private ListeClients getModel() {
        return model;
    }

    private ClientsView getView() {
        return view;
    }

    private void setModel(ListeClients model) {
        this.model = model;
    }

    private void setView(ClientsView view) {
        this.view = view;
    }

    /**
    * @param model 
    * @param view
    */

    // ----------- << method.annotations@AAAAAAGEs3VV6jLdIQk= >>
    // ----------- >>
    public ClientsCtrl(ListeClients model, ClientsView view) {
    // ----------- << method.body@AAAAAAGEs3VV6jLdIQk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3L5wiWcNo0= >>
    // ----------- >>
    public void ajouterClient() {
    // ----------- << method.body@AAAAAAGEs3L5wiWcNo0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3MTDiYD/6k= >>
    // ----------- >>
    public void supprimerClient() {
    // ----------- << method.body@AAAAAAGEs3MTDiYD/6k= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3M09iZzSqI= >>
    // ----------- >>
    public void editerClient() {
    // ----------- << method.body@AAAAAAGEs3M09iZzSqI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEqtnSqgaMqNg= >>
// ----------- >>
}