/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;


import root.model.ListeCommandes;
import root.view.CommandesView;
// ----------- << imports@AAAAAAGEqtmcvAY4/IA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqtmcvAY4/IA= >>
// ----------- >>
public class CommandesCtrl {
    // ----------- << attribute.annotations@AAAAAAGEs3aYkzia554= >>
    // ----------- >>
    private ListeCommandes model;

    // ----------- << attribute.annotations@AAAAAAGEs3N5vid6nvc= >>
    // ----------- >>
    private CommandesView view;

    private ListeCommandes getModel() {
        return model;
    }

    private CommandesView getView() {
        return view;
    }

    private void setModel(ListeCommandes model) {
        this.model = model;
    }

    private void setView(CommandesView view) {
        this.view = view;
    }

    /**
    * @param model 
    * @param view
    */

    // ----------- << method.annotations@AAAAAAGEs3Y9+zfUF54= >>
    // ----------- >>
    public CommandesCtrl(ListeCommandes model, CommandesView view) {
    // ----------- << method.body@AAAAAAGEs3Y9+zfUF54= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3OYBCfx2YM= >>
    // ----------- >>
    public void ajouterCommande() {
    // ----------- << method.body@AAAAAAGEs3OYBCfx2YM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3OsQShYLdA= >>
    // ----------- >>
    public void supprimerCommande() {
    // ----------- << method.body@AAAAAAGEs3OsQShYLdA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3OueyiF610= >>
    // ----------- >>
    public void editerCommande() {
    // ----------- << method.body@AAAAAAGEs3OueyiF610= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEqtmcvAY4/IA= >>
// ----------- >>
}