/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEw3YCQVCT+Vs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEw3YCQVCT+Vs= >>
// ----------- >>
public class CommandesFormCtrl {
    // ----------- << method.annotations@AAAAAAGEw3oyIlFzyAw= >>
    // ----------- >>
    public void enregistrer() {
    // ----------- << method.body@AAAAAAGEw3oyIlFzyAw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw3qPJlF6pT8= >>
    // ----------- >>
    public void cancel() {
    // ----------- << method.body@AAAAAAGEw3qPJlF6pT8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEw3YCQVCT+Vs= >>
// ----------- >>
}