/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;


import root.view.CompteView;
// ----------- << imports@AAAAAAGEqtm1XgZitHk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqtm1XgZitHk= >>
// ----------- >>
public class CompteCtrl {
    // ----------- << attribute.annotations@AAAAAAGEs4PvE7qqWyM= >>
    // ----------- >>
    private CompteView view;

    private CompteView getView() {
        return view;
    }

    private void setView(CompteView view) {
        this.view = view;
    }

    /**
    * @param view
    */

    // ----------- << method.annotations@AAAAAAGEs4QldbtK0Jk= >>
    // ----------- >>
    public CompteCtrl(CompteView view) {
    // ----------- << method.body@AAAAAAGEs4QldbtK0Jk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs4MzE7gwlmU= >>
    // ----------- >>
    public void updateUtilisateur() {
    // ----------- << method.body@AAAAAAGEs4MzE7gwlmU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEqtm1XgZitHk= >>
// ----------- >>
}