/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;


import root.view.ConnexionView;
import root.view.TableaudebordView;
// ----------- << imports@AAAAAAGEqtk7LQW54k0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqtk7LQW54k0= >>
// ----------- >>
public class ConnexionCtrl {
    // ----------- << attribute.annotations@AAAAAAGEqvcyTLf8M4k= >>
    // ----------- >>
    private ConnexionView connexionView;

    // ----------- << attribute.annotations@AAAAAAGEqv73bd1ipyg= >>
    // ----------- >>
    private TableaudebordView tableaudebordView;

    private ConnexionView getConnexionView() {
        return connexionView;
    }

    private TableaudebordView getTableaudebordView() {
        return tableaudebordView;
    }

    private void setConnexionView(ConnexionView connexionView) {
        this.connexionView = connexionView;
    }

    private void setTableaudebordView(TableaudebordView tableaudebordView) {
        this.tableaudebordView = tableaudebordView;
    }

    // ----------- << method.annotations@AAAAAAGEqvoRd9Lc4Ws= >>
    // ----------- >>
    public void verifieIdentifiants() {
    // ----------- << method.body@AAAAAAGEqvoRd9Lc4Ws= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw1xV1DE97Gk= >>
    // ----------- >>
    public void buttonPressed() {
    // ----------- << method.body@AAAAAAGEw1xV1DE97Gk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw13e3TFo6Og= >>
    // ----------- >>
    private boolean valideIdentifiant() {
    // ----------- << method.body@AAAAAAGEw13e3TFo6Og= >>
    // ----------- >>
        // dummy return, waiting for implementation...
        return false;
    }
// ----------- << class.extras@AAAAAAGEqtk7LQW54k0= >>
// ----------- >>
}
