/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;


import root.model.ListeProducteurs;
import root.view.ProducteursView;
// ----------- << imports@AAAAAAGEs1bE3bIB1G4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEs1bE3bIB1G4= >>
// ----------- >>
public class ProducteursCtrl {
    // ----------- << attribute.annotations@AAAAAAGEs4c27NfXL3I= >>
    // ----------- >>
    private ListeProducteurs model;

    // ----------- << attribute.annotations@AAAAAAGEs4c7Q9grkg0= >>
    // ----------- >>
    private ProducteursView view;

    private ListeProducteurs getModel() {
        return model;
    }

    private ProducteursView getView() {
        return view;
    }

    private void setModel(ListeProducteurs model) {
        this.model = model;
    }

    private void setView(ProducteursView view) {
        this.view = view;
    }

    /**
    * @param model 
    * @param view
    */

    // ----------- << method.annotations@AAAAAAGEs4evCtuShfc= >>
    // ----------- >>
    public ProducteursCtrl(ListeProducteurs model, ProducteursView view) {
    // ----------- << method.body@AAAAAAGEs4evCtuShfc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs4gYz91506w= >>
    // ----------- >>
    public void ajouterProducteur() {
    // ----------- << method.body@AAAAAAGEs4gYz91506w= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs4gbIt3NWDc= >>
    // ----------- >>
    public void supprimerProducteur() {
    // ----------- << method.body@AAAAAAGEs4gbIt3NWDc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs4gc/d4hGCQ= >>
    // ----------- >>
    public void editerProducteur() {
    // ----------- << method.body@AAAAAAGEs4gc/d4hGCQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEs1bE3bIB1G4= >>
// ----------- >>
}