/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEw3eMClCjNew= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEw3eMClCjNew= >>
// ----------- >>
public class ProducteursFormCtrl {
    // ----------- << method.annotations@AAAAAAGEw3sm01GeHFg= >>
    // ----------- >>
    public void enregistrer() {
    // ----------- << method.body@AAAAAAGEw3sm01GeHFg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw3s251GlGNk= >>
    // ----------- >>
    public void cancel() {
    // ----------- << method.body@AAAAAAGEw3s251GlGNk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEw3eMClCjNew= >>
// ----------- >>
}