/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;


import root.model.ListeCommandes;
import root.model.ListeTournees;
import root.view.ClientsView;
import root.view.CommandesView;
import root.view.CompteView;
import root.view.TableaudebordView;
import root.view.TourneesView;
// ----------- << imports@AAAAAAGEqtlcFAXkkeU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqtlcFAXkkeU= >>
// ----------- >>
public class TableaudebordCtrl {
    // ----------- << attribute.annotations@AAAAAAGEq63WTrpgnYI= >>
    // ----------- >>
    private ListeTournees listeTournees;

    // ----------- << attribute.annotations@AAAAAAGEs4I7MKLjEFw= >>
    // ----------- >>
    private ListeCommandes listeCommandes;

    // ----------- << attribute.annotations@AAAAAAGEq5T6QLCyK+s= >>
    // ----------- >>
    private TableaudebordView tableaudebordView;

    // ----------- << attribute.annotations@AAAAAAGEq5VShrC7YQQ= >>
    // ----------- >>
    private CommandesView commandesView;

    // ----------- << attribute.annotations@AAAAAAGEq5VU57DBTng= >>
    // ----------- >>
    private TourneesView tourneesView;

    // ----------- << attribute.annotations@AAAAAAGEq5VWR7DHdrY= >>
    // ----------- >>
    private CompteView compteView;

    // ----------- << attribute.annotations@AAAAAAGEq5VX6bDNjVM= >>
    // ----------- >>
    private ClientsView clientsView;

    private ListeTournees getListeTournees() {
        return listeTournees;
    }

    public ListeCommandes getListeCommandes() {
        return listeCommandes;
    }

    private TableaudebordView getTableaudebordView() {
        return tableaudebordView;
    }

    private CommandesView getCommandesView() {
        return commandesView;
    }

    private TourneesView getTourneesView() {
        return tourneesView;
    }

    private CompteView getCompteView() {
        return compteView;
    }

    private ClientsView getClientsView() {
        return clientsView;
    }

    private void setListeTournees(ListeTournees listeTournees) {
        this.listeTournees = listeTournees;
    }

    public void setListeCommandes(ListeCommandes listeCommandes) {
        this.listeCommandes = listeCommandes;
    }

    private void setTableaudebordView(TableaudebordView tableaudebordView) {
        this.tableaudebordView = tableaudebordView;
    }

    private void setCommandesView(CommandesView commandesView) {
        this.commandesView = commandesView;
    }

    private void setTourneesView(TourneesView tourneesView) {
        this.tourneesView = tourneesView;
    }

    private void setCompteView(CompteView compteView) {
        this.compteView = compteView;
    }

    private void setClientsView(ClientsView clientsView) {
        this.clientsView = clientsView;
    }

    // ----------- << method.annotations@AAAAAAGEq6+aW79pjnM= >>
    // ----------- >>
    public void goToMenuCommandes() {
    // ----------- << method.body@AAAAAAGEq6+aW79pjnM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEq7Arb8bCGS0= >>
    // ----------- >>
    public void goToMenuTournees() {
    // ----------- << method.body@AAAAAAGEq7Arb8bCGS0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEq7AubcdqZ4A= >>
    // ----------- >>
    public void goToMenuCompte() {
    // ----------- << method.body@AAAAAAGEq7AubcdqZ4A= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEq7AwPsgSb6c= >>
    // ----------- >>
    public void goToMenuClients() {
    // ----------- << method.body@AAAAAAGEq7AwPsgSb6c= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3EjrhUUSxM= >>
    // ----------- >>
    public void ajouterTournee() {
    // ----------- << method.body@AAAAAAGEs3EjrhUUSxM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3E4KRb7BWk= >>
    // ----------- >>
    public void supprimerTournee() {
    // ----------- << method.body@AAAAAAGEs3E4KRb7BWk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3FaPhk8jew= >>
    // ----------- >>
    public void editerTournee() {
    // ----------- << method.body@AAAAAAGEs3FaPhk8jew= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3F44xsj3/k= >>
    // ----------- >>
    public void ajouterCommande() {
    // ----------- << method.body@AAAAAAGEs3F44xsj3/k= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3GnfR0KoCQ= >>
    // ----------- >>
    public void supprimerCommande() {
    // ----------- << method.body@AAAAAAGEs3GnfR0KoCQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs3HBlR9aXtA= >>
    // ----------- >>
    public void editerCommande() {
    // ----------- << method.body@AAAAAAGEs3HBlR9aXtA= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEqtlcFAXkkeU= >>
// ----------- >>
}