/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;


import root.model.ListeTournees;
import root.view.TourneesView;
// ----------- << imports@AAAAAAGEqtmBawYOTXI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqtmBawYOTXI= >>
// ----------- >>
public class TourneesCtrl {
    // ----------- << attribute.annotations@AAAAAAGEs33/WGv0BqE= >>
    // ----------- >>
    private ListeTournees model;

    // ----------- << attribute.annotations@AAAAAAGEs34kuWy7evA= >>
    // ----------- >>
    private TourneesView view;

    private ListeTournees getModel() {
        return model;
    }

    private TourneesView getView() {
        return view;
    }

    private void setModel(ListeTournees model) {
        this.model = model;
    }

    private void setView(TourneesView view) {
        this.view = view;
    }

    /**
    * @param model 
    * @param view
    */

    // ----------- << method.annotations@AAAAAAGEs35fem9wIX0= >>
    // ----------- >>
    public TourneesCtrl(ListeTournees model, TourneesView view) {
    // ----------- << method.body@AAAAAAGEs35fem9wIX0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs37AHnFQQGc= >>
    // ----------- >>
    public void ajouterTournee() {
    // ----------- << method.body@AAAAAAGEs37AHnFQQGc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs37zUXMTwns= >>
    // ----------- >>
    public void supprimerTournee() {
    // ----------- << method.body@AAAAAAGEs37zUXMTwns= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEs37103Nnlj8= >>
    // ----------- >>
    public void editerTournee() {
    // ----------- << method.body@AAAAAAGEs37103Nnlj8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEqtmBawYOTXI= >>
// ----------- >>
}