/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEw3aavVCbF1E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEw3aavVCbF1E= >>
// ----------- >>
public class TourneesFormCtrl {
    // ----------- << method.annotations@AAAAAAGEw3rFGlGBzaI= >>
    // ----------- >>
    public void enregistrer() {
    // ----------- << method.body@AAAAAAGEw3rFGlGBzaI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw3rqrFGIp1U= >>
    // ----------- >>
    public void cancel() {
    // ----------- << method.body@AAAAAAGEw3rqrFGIp1U= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEw3aavVCbF1E= >>
// ----------- >>
}