/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEtgYrZ/5woB4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEtgYrZ/5woB4= >>
// ----------- >>
public class VehiculesCtrl {
// ----------- << class.extras@AAAAAAGEtgYrZ/5woB4= >>
// ----------- >>
}