/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.controller;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEw3ZWS1CXDrY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEw3ZWS1CXDrY= >>
// ----------- >>
public class VehiculesFormCtrl {
    // ----------- << method.annotations@AAAAAAGEw3tM9lGsH4M= >>
    // ----------- >>
    public void enregistrer() {
    // ----------- << method.body@AAAAAAGEw3tM9lGsH4M= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw3tauVGzJdo= >>
    // ----------- >>
    public void cancel() {
    // ----------- << method.body@AAAAAAGEw3tauVGzJdo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEw3ZWS1CXDrY= >>
// ----------- >>
}