/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;

import javafx.scene.control.*;



// ----------- << imports@AAAAAAGEsum/IA6c5ac= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IA6c5ac= >>
// ----------- >>
public class ClientsView {
    // ----------- << attribute.annotations@AAAAAAGEtfEFKP0mARY= >>
    // ----------- >>
    private MenuBar menu;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6YqTM= >>
    // ----------- >>
    private ListView listeClients;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6ZQz8= >>
    // ----------- >>
    private Button ajouterClient;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6avZw= >>
    // ----------- >>
    private Button supprimerClient;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6bplQ= >>
    // ----------- >>
    private Button editerClient;

    private MenuBar getMenu() {
        return menu;
    }

    private ListView getListeClients() {
        return listeClients;
    }

    private Button getAjouterClient() {
        return ajouterClient;
    }

    private Button getSupprimerClient() {
        return supprimerClient;
    }

    private Button getEditerClient() {
        return editerClient;
    }

    private void setMenu(MenuBar menu) {
        this.menu = menu;
    }

    private void setListeClients(ListView listeClients) {
        this.listeClients = listeClients;
    }

    private void setAjouterClient(Button ajouterClient) {
        this.ajouterClient = ajouterClient;
    }

    private void setSupprimerClient(Button supprimerClient) {
        this.supprimerClient = supprimerClient;
    }

    private void setEditerClient(Button editerClient) {
        this.editerClient = editerClient;
    }

// ----------- << class.extras@AAAAAAGEsum/IA6c5ac= >>
// ----------- >>
}