/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;


import root.model.Adresse;
// ----------- << imports@AAAAAAGEtYXV9fbCK0U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEtYXV9fbCK0U= >>
// ----------- >>
public class ClientsFormView {
    // ----------- << attribute.annotations@AAAAAAGEtalodPrFtfM= >>
    // ----------- >>
    private Label nomLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYuWKfjLhSM= >>
    // ----------- >>
    private TextField nom;

    // ----------- << attribute.annotations@AAAAAAGEtalrsPrLudA= >>
    // ----------- >>
    private Label prenomLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYuYPfjRu3k= >>
    // ----------- >>
    private TextField prenom;

    // ----------- << attribute.annotations@AAAAAAGEtaluQPrR3pE= >>
    // ----------- >>
    private Label numTelLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYuamPjXwUE= >>
    // ----------- >>
    private TextField numTel;

    // ----------- << attribute.annotations@AAAAAAGEtaqf4fsD8p8= >>
    // ----------- >>
    private Label coordonneesLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYuca/jd2KU= >>
    // ----------- >>
    private TextField latitude;

    // ----------- << attribute.annotations@AAAAAAGEtYzP7vjpAQQ= >>
    // ----------- >>
    private TextField longitude;

    // ----------- << attribute.annotations@AAAAAAGEtalxGPrXdSU= >>
    // ----------- >>
    private Adresse adresseLabel;

    // ----------- << attribute.annotations@AAAAAAGEtY1wSvj4n00= >>
    // ----------- >>
    private TextField adresse;

    // ----------- << attribute.annotations@AAAAAAGEw5b+K1smlh0= >>
    // ----------- >>
    private Label villeLabel;

    // ----------- << attribute.annotations@AAAAAAGEw5cDa1ssMI4= >>
    // ----------- >>
    private TextField ville;

    // ----------- << attribute.annotations@AAAAAAGEw5dnK1s5hvk= >>
    // ----------- >>
    private Label codePostLabel;

    // ----------- << attribute.annotations@AAAAAAGEw5drA1s/3Dk= >>
    // ----------- >>
    private TextField codePost;

    // ----------- << attribute.annotations@AAAAAAGEtehBoPw2dmA= >>
    // ----------- >>
    private Button enregistrer;

    // ----------- << attribute.annotations@AAAAAAGEtehuVPw94ec= >>
    // ----------- >>
    private Button annuler;

    private Label getNomLabel() {
        return nomLabel;
    }

    private TextField getNom() {
        return nom;
    }

    private Label getPrenomLabel() {
        return prenomLabel;
    }

    private TextField getPrenom() {
        return prenom;
    }

    private Label getNumTelLabel() {
        return numTelLabel;
    }

    private TextField getNumTel() {
        return numTel;
    }

    private Label getCoordonneesLabel() {
        return coordonneesLabel;
    }

    private TextField getLatitude() {
        return latitude;
    }

    private TextField getLongitude() {
        return longitude;
    }

    private Adresse getAdresseLabel() {
        return adresseLabel;
    }

    private TextField getAdresse() {
        return adresse;
    }

    private Label getVilleLabel() {
        return villeLabel;
    }

    private TextField getVille() {
        return ville;
    }

    private Label getCodePostLabel() {
        return codePostLabel;
    }

    private TextField getCodePost() {
        return codePost;
    }

    private Button getEnregistrer() {
        return enregistrer;
    }

    private Button getAnnuler() {
        return annuler;
    }

    private void setNomLabel(Label nomLabel) {
        this.nomLabel = nomLabel;
    }

    private void setNom(TextField nom) {
        this.nom = nom;
    }

    private void setPrenomLabel(Label prenomLabel) {
        this.prenomLabel = prenomLabel;
    }

    private void setPrenom(TextField prenom) {
        this.prenom = prenom;
    }

    private void setNumTelLabel(Label numTelLabel) {
        this.numTelLabel = numTelLabel;
    }

    private void setNumTel(TextField numTel) {
        this.numTel = numTel;
    }

    private void setCoordonneesLabel(Label coordonneesLabel) {
        this.coordonneesLabel = coordonneesLabel;
    }

    private void setLatitude(TextField latitude) {
        this.latitude = latitude;
    }

    private void setLongitude(TextField longitude) {
        this.longitude = longitude;
    }

    private void setAdresseLabel(Adresse adresseLabel) {
        this.adresseLabel = adresseLabel;
    }

    private void setAdresse(TextField adresse) {
        this.adresse = adresse;
    }

    private void setVilleLabel(Label villeLabel) {
        this.villeLabel = villeLabel;
    }

    private void setVille(TextField ville) {
        this.ville = ville;
    }

    private void setCodePostLabel(Label codePostLabel) {
        this.codePostLabel = codePostLabel;
    }

    private void setCodePost(TextField codePost) {
        this.codePost = codePost;
    }

    private void setEnregistrer(Button enregistrer) {
        this.enregistrer = enregistrer;
    }

    private void setAnnuler(Button annuler) {
        this.annuler = annuler;
    }

    // ----------- << method.annotations@AAAAAAGEw4L4VFNcBOc= >>
    // ----------- >>
    public void getNom() {
    // ----------- << method.body@AAAAAAGEw4L4VFNcBOc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw4MMYFNghhg= >>
    // ----------- >>
    public void getPrenom() {
    // ----------- << method.body@AAAAAAGEw4MMYFNghhg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw4MhpFNj+sI= >>
    // ----------- >>
    public void getNumTel() {
    // ----------- << method.body@AAAAAAGEw4MhpFNj+sI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw4NBolNnU30= >>
    // ----------- >>
    public void getLatitude() {
    // ----------- << method.body@AAAAAAGEw4NBolNnU30= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw4NawVNqXgc= >>
    // ----------- >>
    public void getLongitude() {
    // ----------- << method.body@AAAAAAGEw4NawVNqXgc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw4Oi6lOCkDU= >>
    // ----------- >>
    public void getAdresse() {
    // ----------- << method.body@AAAAAAGEw4Oi6lOCkDU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw4QCR1Oy3us= >>
    // ----------- >>
    public void getVille() {
    // ----------- << method.body@AAAAAAGEw4QCR1Oy3us= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw5RdMlqpeJU= >>
    // ----------- >>
    public void getCodePost() {
    // ----------- << method.body@AAAAAAGEw5RdMlqpeJU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw75KOGKuxpw= >>
    // ----------- >>
    public void setMessageErreur() {
    // ----------- << method.body@AAAAAAGEw75KOGKuxpw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEw75nfGKzOPE= >>
    // ----------- >>
    public void setMessageOk() {
    // ----------- << method.body@AAAAAAGEw75nfGKzOPE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEtYXV9fbCK0U= >>
// ----------- >>
}