/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEsum/IA6RiN4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IA6RiN4= >>
// ----------- >>
public class CommandesView {
    // ----------- << attribute.annotations@AAAAAAGEte+Eafz2nt8= >>
    // ----------- >>
    private MenuBar menu;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6N6Gg= >>
    // ----------- >>
    private ListView listeCommandes;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6Okho= >>
    // ----------- >>
    private Button ajouterCommande;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6PR3I= >>
    // ----------- >>
    private Button supprimerCommande;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6Q75g= >>
    // ----------- >>
    private Button editerCommande;

    private MenuBar getMenu() {
        return menu;
    }

    private ListView getListeCommandes() {
        return listeCommandes;
    }

    private Button getAjouterCommande() {
        return ajouterCommande;
    }

    private Button getSupprimerCommande() {
        return supprimerCommande;
    }

    private Button getEditerCommande() {
        return editerCommande;
    }

    private void setMenu(MenuBar menu) {
        this.menu = menu;
    }

    private void setListeCommandes(ListView listeCommandes) {
        this.listeCommandes = listeCommandes;
    }

    private void setAjouterCommande(Button ajouterCommande) {
        this.ajouterCommande = ajouterCommande;
    }

    private void setSupprimerCommande(Button supprimerCommande) {
        this.supprimerCommande = supprimerCommande;
    }

    private void setEditerCommande(Button editerCommande) {
        this.editerCommande = editerCommande;
    }

// ----------- << class.extras@AAAAAAGEsum/IA6RiN4= >>
// ----------- >>
}