/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;

import javafx.scene.control.*;




// ----------- << imports@AAAAAAGEsum/IQ6qlW8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IQ6qlW8= >>
// ----------- >>
public class CommandesFormView {
    // ----------- << attribute.annotations@AAAAAAGEterHw/yKrnY= >>
    // ----------- >>
    private Label libelleLabel;

    // ----------- << attribute.annotations@AAAAAAGEteqZUPyBBU4= >>
    // ----------- >>
    private TextField libelle;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6n7kI= >>
    // ----------- >>
    private Label poidsLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6ofRs= >>
    // ----------- >>
    private TextField poids;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6hYqU= >>
    // ----------- >>
    private Label clientLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6jy/s= >>
    // ----------- >>
    private Label LblVoiture;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6iCeU= >>
    // ----------- >>
    private ChoiceBox client;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6k2xc= >>
    // ----------- >>
    private ChoiceBox VoitureForm;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6l4AY= >>
    // ----------- >>
    private Label dateLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6m/EY= >>
    // ----------- >>
    private DatePicker date;

    // ----------- << attribute.annotations@AAAAAAGEtexTD/zXkLs= >>
    // ----------- >>
    private Label heureDebLabel;

    // ----------- << attribute.annotations@AAAAAAGEteu/pvy/wns= >>
    // ----------- >>
    private TextField heureDeb;

    // ----------- << attribute.annotations@AAAAAAGEtfceZP4K1OA= >>
    // ----------- >>
    private Label heureFinLabel;

    // ----------- << attribute.annotations@AAAAAAGEtev87/zGNf8= >>
    // ----------- >>
    private TextField heureFin;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6prjQ= >>
    // ----------- >>
    private Button enregistrer;

    // ----------- << attribute.annotations@AAAAAAGEteoaO/x5+80= >>
    // ----------- >>
    private Button annuler;

    private Label getLibelleLabel() {
        return libelleLabel;
    }

    private TextField getLibelle() {
        return libelle;
    }

    private Label getPoidsLabel() {
        return poidsLabel;
    }

    private TextField getPoids() {
        return poids;
    }

    private Label getClientLabel() {
        return clientLabel;
    }

    private Label getLblVoiture() {
        return LblVoiture;
    }

    private ChoiceBox getClient() {
        return client;
    }

    private ChoiceBox getVoitureForm() {
        return VoitureForm;
    }

    private Label getDateLabel() {
        return dateLabel;
    }

    private DatePicker getDate() {
        return date;
    }

    private Label getHeureDebLabel() {
        return heureDebLabel;
    }

    private TextField getHeureDeb() {
        return heureDeb;
    }

    private Label getHeureFinLabel() {
        return heureFinLabel;
    }

    private TextField getHeureFin() {
        return heureFin;
    }

    private Button getEnregistrer() {
        return enregistrer;
    }

    private Button getAnnuler() {
        return annuler;
    }

    private void setLibelleLabel(Label libelleLabel) {
        this.libelleLabel = libelleLabel;
    }

    private void setLibelle(TextField libelle) {
        this.libelle = libelle;
    }

    private void setPoidsLabel(Label poidsLabel) {
        this.poidsLabel = poidsLabel;
    }

    private void setPoids(TextField poids) {
        this.poids = poids;
    }

    private void setClientLabel(Label clientLabel) {
        this.clientLabel = clientLabel;
    }

    private void setLblVoiture(Label LblVoiture) {
        this.LblVoiture = LblVoiture;
    }

    private void setClient(ChoiceBox client) {
        this.client = client;
    }

    private void setVoitureForm(ChoiceBox VoitureForm) {
        this.VoitureForm = VoitureForm;
    }

    private void setDateLabel(Label dateLabel) {
        this.dateLabel = dateLabel;
    }

    private void setDate(DatePicker date) {
        this.date = date;
    }

    private void setHeureDebLabel(Label heureDebLabel) {
        this.heureDebLabel = heureDebLabel;
    }

    private void setHeureDeb(TextField heureDeb) {
        this.heureDeb = heureDeb;
    }

    private void setHeureFinLabel(Label heureFinLabel) {
        this.heureFinLabel = heureFinLabel;
    }

    private void setHeureFin(TextField heureFin) {
        this.heureFin = heureFin;
    }

    private void setEnregistrer(Button enregistrer) {
        this.enregistrer = enregistrer;
    }

    private void setAnnuler(Button annuler) {
        this.annuler = annuler;
    }

// ----------- << class.extras@AAAAAAGEsum/IQ6qlW8= >>
// ----------- >>
}