/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEsum/IQ6gbkg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IQ6gbkg= >>
// ----------- >>
public class CompteView {
    // ----------- << attribute.annotations@AAAAAAGEte/1n/0O3ec= >>
    // ----------- >>
    private MenuBar menu;

    // ----------- << attribute.annotations@AAAAAAGEtfF+BP0yCR8= >>
    // ----------- >>
    private TextField email;

    // ----------- << attribute.annotations@AAAAAAGEtfIAG/05JOg= >>
    // ----------- >>
    private Label emailLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6dxPA= >>
    // ----------- >>
    private Label motdepasseLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6eI3g= >>
    // ----------- >>
    private PasswordField motdepasse;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6fIzc= >>
    // ----------- >>
    private Button enregistrer;

    // ----------- << attribute.annotations@AAAAAAGEtfiaZ/4Vi2s= >>
    // ----------- >>
    private Button annuler;

    private MenuBar getMenu() {
        return menu;
    }

    private TextField getEmail() {
        return email;
    }

    private Label getEmailLabel() {
        return emailLabel;
    }

    private Label getMotdepasseLabel() {
        return motdepasseLabel;
    }

    private PasswordField getMotdepasse() {
        return motdepasse;
    }

    private Button getEnregistrer() {
        return enregistrer;
    }

    private Button getAnnuler() {
        return annuler;
    }

    private void setMenu(MenuBar menu) {
        this.menu = menu;
    }

    private void setEmail(TextField email) {
        this.email = email;
    }

    private void setEmailLabel(Label emailLabel) {
        this.emailLabel = emailLabel;
    }

    private void setMotdepasseLabel(Label motdepasseLabel) {
        this.motdepasseLabel = motdepasseLabel;
    }

    private void setMotdepasse(PasswordField motdepasse) {
        this.motdepasse = motdepasse;
    }

    private void setEnregistrer(Button enregistrer) {
        this.enregistrer = enregistrer;
    }

    private void setAnnuler(Button annuler) {
        this.annuler = annuler;
    }

// ----------- << class.extras@AAAAAAGEsum/IQ6gbkg= >>
// ----------- >>
}