/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */

package root.view;

import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;




// ----------- << imports@AAAAAAGEsum/IA6CD5o= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IA6CD5o= >>
// ----------- >>

/**
 * Classe de vue pour la connexion.
 */
public class ConnexionView {
  // ----------- << attribute.annotations@AAAAAAGEta+GJ/uctss= >>
  // ----------- >>
  private Label identifiantLabel;

  // ----------- << attribute.annotations@AAAAAAGEsum/IA566vE= >>
  // ----------- >>
  private TextField identifiant;

  // ----------- << attribute.annotations@AAAAAAGEta+9svuk5bo= >>
  // ----------- >>
  private Label motdepasseLabel;

  // ----------- << attribute.annotations@AAAAAAGEsum/IA57tX0= >>
  // ----------- >>
  private PasswordField motdepasse;

  // ----------- << attribute.annotations@AAAAAAGEta/kq/urDLg= >>
  // ----------- >>
  private Label modeLabel;

  // ----------- << attribute.annotations@AAAAAAGEs0wNFlbAQ2U= >>
  // ----------- >>
  private CheckBox mode;

  // ----------- << attribute.annotations@AAAAAAGEsum/IA59ICs= >>
  // ----------- >>
  private Label messageErreur;

  // ----------- << attribute.annotations@AAAAAAGEsum/IA58WVs= >>
  // ----------- >>
  private Button seConnecter;

  private Label getIdentifiantLabel() {
    return identifiantLabel;
  }

  private TextField getIdentifiantForm() {
    return identifiant;
  }

  private Label getMotdepasseLabel() {
    return motdepasseLabel;
  }

  private PasswordField getMotdepasse() {
    return motdepasse;
  }

  private Label getModeLabel() {
    return modeLabel;
  }

  private CheckBox getMode() {
    return mode;
  }

  private Label getMessageErreur() {
    return messageErreur;
  }

  private Button getSeConnecter() {
    return seConnecter;
  }

  private void setIdentifiantLabel(Label identifiantLabel) {
    this.identifiantLabel = identifiantLabel;
  }

  private void setIdentifiant(TextField identifiant) {
    this.identifiant = identifiant;
  }

  private void setMotdepasseLabel(Label motdepasseLabel) {
    this.motdepasseLabel = motdepasseLabel;
  }

  private void setMotdepasse(PasswordField motdepasse) {
    this.motdepasse = motdepasse;
  }

  private void setModeLabel(Label modeLabel) {
    this.modeLabel = modeLabel;
  }

  private void setMode(CheckBox mode) {
    this.mode = mode;
  }

  private void setMessageErreur(Label messageErreur) {
    this.messageErreur = messageErreur;
  }

  private void setSeConnecter(Button seConnecter) {
    this.seConnecter = seConnecter;
  }

  // ----------- << method.annotations@AAAAAAGEw1ypqDFEVPI= >>
  // ----------- >>

  /**
   * Retourne l'identifiant saisi.
   *
   * @return identifiant saisi
   */
  public String getIdentifiant() {
    // ----------- << method.body@AAAAAAGEw1ypqDFEVPI= >>
    // ----------- >>
    return null;
  }
  // ----------- << method.annotations@AAAAAAGEw1yuFTFKf9M= >>
  // ----------- >>

  /**
   * Retourne le mot de passe saisi.
   *
   * @return mot de passe saisi
   */
  public String getMdp() {
    // ----------- << method.body@AAAAAAGEw1yuFTFKf9M= >>
    // ----------- >>
    return null;
  }
  // ----------- << method.annotations@AAAAAAGEw1ziYzFZ4cs= >>
  // ----------- >>

  /**
   * Retourne le mode de connexion.
   *
   * @return mode de connexion
   */
  public String getConnexionMode() {
    // ----------- << method.body@AAAAAAGEw1ziYzFZ4cs= >>
    // ----------- >>
    return null;
  }
  // ----------- << method.annotations@AAAAAAGEw16Q2DF7rPA= >>
  // ----------- >>
}