/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;


import javafx.scene.control.*;



// ----------- << imports@AAAAAAGEtYZ9MvbxXHw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEtYZ9MvbxXHw= >>
// ----------- >>
public class ProducteursFormView {
    // ----------- << attribute.annotations@AAAAAAGEtZtCtPmKfn0= >>
    // ----------- >>
    private Label SIRETLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYh78PifSsY= >>
    // ----------- >>
    private TextField SIRET;

    // ----------- << attribute.annotations@AAAAAAGEtZtF/vmQN1Y= >>
    // ----------- >>
    private Label nomLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYkfm/imnGk= >>
    // ----------- >>
    private TextField nom;

    // ----------- << attribute.annotations@AAAAAAGEtZtIEvmWNAA= >>
    // ----------- >>
    private Label prenomLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYlFx/itphE= >>
    // ----------- >>
    private TextField prenom;

    // ----------- << attribute.annotations@AAAAAAGEtZtKTPmc2GY= >>
    // ----------- >>
    private Label numTelLabel;

    // ----------- << attribute.annotations@AAAAAAGEtYlH0/iz3GY= >>
    // ----------- >>
    private TextField numTel;

    // ----------- << attribute.annotations@AAAAAAGEtY8iVfkFOrw= >>
    // ----------- >>
    private TextField adresseVoie;

    // ----------- << attribute.annotations@AAAAAAGEtZy7Pvm9KA0= >>
    // ----------- >>
    private Label adresseLabel;

    // ----------- << attribute.annotations@AAAAAAGEtZlCKPlmZ0Q= >>
    // ----------- >>
    private TextField adresse;

    // ----------- << attribute.annotations@AAAAAAGEtYpkHPjDSKw= >>
    // ----------- >>
    private Button enregistrer;

    // ----------- << attribute.annotations@AAAAAAGEtel7+vxuy4A= >>
    // ----------- >>
    private Button annuler;

    private Label getSIRETLabel() {
        return SIRETLabel;
    }

    private TextField getSIRET() {
        return SIRET;
    }

    private Label getNomLabel() {
        return nomLabel;
    }

    private TextField getNom() {
        return nom;
    }

    private Label getPrenomLabel() {
        return prenomLabel;
    }

    private TextField getPrenom() {
        return prenom;
    }

    private Label getNumTelLabel() {
        return numTelLabel;
    }

    private TextField getNumTel() {
        return numTel;
    }

    private TextField getAdresseVoie() {
        return adresseVoie;
    }

    private Label getAdresseLabel() {
        return adresseLabel;
    }

    private TextField getAdresse() {
        return adresse;
    }

    private Button getEnregistrer() {
        return enregistrer;
    }

    private Button getAnnuler() {
        return annuler;
    }

    private void setSIRETLabel(Label SIRETLabel) {
        this.SIRETLabel = SIRETLabel;
    }

    private void setSIRET(TextField SIRET) {
        this.SIRET = SIRET;
    }

    private void setNomLabel(Label nomLabel) {
        this.nomLabel = nomLabel;
    }

    private void setNom(TextField nom) {
        this.nom = nom;
    }

    private void setPrenomLabel(Label prenomLabel) {
        this.prenomLabel = prenomLabel;
    }

    private void setPrenom(TextField prenom) {
        this.prenom = prenom;
    }

    private void setNumTelLabel(Label numTelLabel) {
        this.numTelLabel = numTelLabel;
    }

    private void setNumTel(TextField numTel) {
        this.numTel = numTel;
    }

    private void setAdresseVoie(TextField adresseVoie) {
        this.adresseVoie = adresseVoie;
    }

    private void setAdresseLabel(Label adresseLabel) {
        this.adresseLabel = adresseLabel;
    }

    private void setAdresse(TextField adresse) {
        this.adresse = adresse;
    }

    private void setEnregistrer(Button enregistrer) {
        this.enregistrer = enregistrer;
    }

    private void setAnnuler(Button annuler) {
        this.annuler = annuler;
    }

// ----------- << class.extras@AAAAAAGEtYZ9MvbxXHw= >>
// ----------- >>
}