/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;


import javafx.scene.control.*;


// ----------- << imports@AAAAAAGEs1OLJaBsOWI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEs1OLJaBsOWI= >>
// ----------- >>
public class ProducteursView {
    // ----------- << attribute.annotations@AAAAAAGEtfD1c/0bVYk= >>
    // ----------- >>
    private MenuBar menu;

    // ----------- << attribute.annotations@AAAAAAGEs1O1d6CX7Lo= >>
    // ----------- >>
    private ListView listeProducteurs;

    // ----------- << attribute.annotations@AAAAAAGEs1O3Y6CdZT4= >>
    // ----------- >>
    private Button ajouterProducteur;

    // ----------- << attribute.annotations@AAAAAAGEs1O5CqCjKjg= >>
    // ----------- >>
    private Button supprimerProducteur;

    // ----------- << attribute.annotations@AAAAAAGEs1O6v6CpNH0= >>
    // ----------- >>
    private Button editerProducteur;

    private MenuBar getMenu() {
        return menu;
    }

    private ListView getListeProducteurs() {
        return listeProducteurs;
    }

    private Button getAjouterProducteur() {
        return ajouterProducteur;
    }

    private Button getSupprimerProducteur() {
        return supprimerProducteur;
    }

    private Button getEditerProducteur() {
        return editerProducteur;
    }

    private void setMenu(MenuBar menu) {
        this.menu = menu;
    }

    private void setListeProducteurs(ListView listeProducteurs) {
        this.listeProducteurs = listeProducteurs;
    }

    private void setAjouterProducteur(Button ajouterProducteur) {
        this.ajouterProducteur = ajouterProducteur;
    }

    private void setSupprimerProducteur(Button supprimerProducteur) {
        this.supprimerProducteur = supprimerProducteur;
    }

    private void setEditerProducteur(Button editerProducteur) {
        this.editerProducteur = editerProducteur;
    }

// ----------- << class.extras@AAAAAAGEs1OLJaBsOWI= >>
// ----------- >>
}