/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEsum/IA6M8Ho= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IA6M8Ho= >>
// ----------- >>
public class TableaudebordView {
    // ----------- << attribute.annotations@AAAAAAGEsum/IA6DQ4I= >>
    // ----------- >>
    private MenuBar menu;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6Em9U= >>
    // ----------- >>
    private ListView listeTournees;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6FHcs= >>
    // ----------- >>
    private ListView listeCommandes;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6GC3w= >>
    // ----------- >>
    private Button ajouterTournee;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6HB3s= >>
    // ----------- >>
    private Button supprimerTournee;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6IvEY= >>
    // ----------- >>
    private Button editerTournee;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6J9Yc= >>
    // ----------- >>
    private Button ajouterCommande;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6KxyU= >>
    // ----------- >>
    private Button supprimerCommande;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6LUVI= >>
    // ----------- >>
    private Button editerCommande;

    private MenuBar getMenu() {
        return menu;
    }

    private ListView getListeTournees() {
        return listeTournees;
    }

    private ListView getListeCommandes() {
        return listeCommandes;
    }

    private Button getAjouterTournee() {
        return ajouterTournee;
    }

    private Button getSupprimerTournee() {
        return supprimerTournee;
    }

    private Button getEditerTournee() {
        return editerTournee;
    }

    private Button getAjouterCommande() {
        return ajouterCommande;
    }

    private Button getSupprimerCommande() {
        return supprimerCommande;
    }

    private Button getEditerCommande() {
        return editerCommande;
    }

    private void setMenu(MenuBar menu) {
        this.menu = menu;
    }

    private void setListeTournees(ListView listeTournees) {
        this.listeTournees = listeTournees;
    }

    private void setListeCommandes(ListView listeCommandes) {
        this.listeCommandes = listeCommandes;
    }

    private void setAjouterTournee(Button ajouterTournee) {
        this.ajouterTournee = ajouterTournee;
    }

    private void setSupprimerTournee(Button supprimerTournee) {
        this.supprimerTournee = supprimerTournee;
    }

    private void setEditerTournee(Button editerTournee) {
        this.editerTournee = editerTournee;
    }

    private void setAjouterCommande(Button ajouterCommande) {
        this.ajouterCommande = ajouterCommande;
    }

    private void setSupprimerCommande(Button supprimerCommande) {
        this.supprimerCommande = supprimerCommande;
    }

    private void setEditerCommande(Button editerCommande) {
        this.editerCommande = editerCommande;
    }

// ----------- << class.extras@AAAAAAGEsum/IA6M8Ho= >>
// ----------- >>
}