/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEsum/IQ60xAo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IQ60xAo= >>
// ----------- >>
public class TourneesFormView {
    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6rwtk= >>
    // ----------- >>
    private TextField ID;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6siyc= >>
    // ----------- >>
    private TextField mdp;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6tkE8= >>
    // ----------- >>
    private Label IDLbl;

    // ----------- << attribute.annotations@AAAAAAGEtfxfWP5O1Ow= >>
    // ----------- >>
    private Label libelleLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6up58= >>
    // ----------- >>
    private Label IDMdp;

    // ----------- << attribute.annotations@AAAAAAGEtfxiL/5UZtI= >>
    // ----------- >>
    private TextField libelle;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6w1qU= >>
    // ----------- >>
    private Label dateLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6xcNk= >>
    // ----------- >>
    private DatePicker date;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6yhGw= >>
    // ----------- >>
    private Label vehiculeLabel;

    // ----------- << attribute.annotations@AAAAAAGEsum/IQ6zGKw= >>
    // ----------- >>
    private ChoiceBox vehicule;

    private TextField getID() {
        return ID;
    }

    private TextField getMdp() {
        return mdp;
    }

    private Label getIDLbl() {
        return IDLbl;
    }

    private Label getLibelleLabel() {
        return libelleLabel;
    }

    private Label getIDMdp() {
        return IDMdp;
    }

    private TextField getLibelle() {
        return libelle;
    }

    private Label getDateLabel() {
        return dateLabel;
    }

    private DatePicker getDate() {
        return date;
    }

    private Label getVehiculeLabel() {
        return vehiculeLabel;
    }

    private ChoiceBox getVehicule() {
        return vehicule;
    }

    private void setID(TextField ID) {
        this.ID = ID;
    }

    private void setMdp(TextField mdp) {
        this.mdp = mdp;
    }

    private void setIDLbl(Label IDLbl) {
        this.IDLbl = IDLbl;
    }

    private void setLibelleLabel(Label libelleLabel) {
        this.libelleLabel = libelleLabel;
    }

    private void setIDMdp(Label IDMdp) {
        this.IDMdp = IDMdp;
    }

    private void setLibelle(TextField libelle) {
        this.libelle = libelle;
    }

    private void setDateLabel(Label dateLabel) {
        this.dateLabel = dateLabel;
    }

    private void setDate(DatePicker date) {
        this.date = date;
    }

    private void setVehiculeLabel(Label vehiculeLabel) {
        this.vehiculeLabel = vehiculeLabel;
    }

    private void setVehicule(ChoiceBox vehicule) {
        this.vehicule = vehicule;
    }

// ----------- << class.extras@AAAAAAGEsum/IQ60xAo= >>
// ----------- >>
}