/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;


import javafx.scene.control.*;



// ----------- << imports@AAAAAAGEsum/IA6XFYs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEsum/IA6XFYs= >>
// ----------- >>
public class TourneesView {
    // ----------- << attribute.annotations@AAAAAAGEte+7AP0Brvo= >>
    // ----------- >>
    private MenuBar menu;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6S0tw= >>
    // ----------- >>
    private ListView listeTournees;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6TsXg= >>
    // ----------- >>
    private Button ajouterTournee;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6UjfY= >>
    // ----------- >>
    private Button supprimerTournee;

    // ----------- << attribute.annotations@AAAAAAGEsum/IA6VXBM= >>
    // ----------- >>
    private Button editerTournee;

    private MenuBar getMenu() {
        return menu;
    }

    private ListView getListeTournees() {
        return listeTournees;
    }

    private Button getAjouterTournee() {
        return ajouterTournee;
    }

    private Button getSupprimerTournee() {
        return supprimerTournee;
    }

    private Button getEditerTournee() {
        return editerTournee;
    }

    private void setMenu(MenuBar menu) {
        this.menu = menu;
    }

    private void setListeTournees(ListView listeTournees) {
        this.listeTournees = listeTournees;
    }

    private void setAjouterTournee(Button ajouterTournee) {
        this.ajouterTournee = ajouterTournee;
    }

    private void setSupprimerTournee(Button supprimerTournee) {
        this.supprimerTournee = supprimerTournee;
    }

    private void setEditerTournee(Button editerTournee) {
        this.editerTournee = editerTournee;
    }

// ----------- << class.extras@AAAAAAGEsum/IA6XFYs= >>
// ----------- >>
}