/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;


import javafx.scene.control.*;


// ----------- << imports@AAAAAAGEtfVLk/2f09A= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEtfVLk/2f09A= >>
// ----------- >>
public class VehiculesFormView {
    // ----------- << attribute.annotations@AAAAAAGEtfWSRP3MHK0= >>
    // ----------- >>
    private Label immatLabel;

    // ----------- << attribute.annotations@AAAAAAGEtfWUnv3SD8I= >>
    // ----------- >>
    private TextField immat;

    // ----------- << attribute.annotations@AAAAAAGEtfWXwv3YRLs= >>
    // ----------- >>
    private Label poidsLabel;

    // ----------- << attribute.annotations@AAAAAAGEtfWZeP3eaKs= >>
    // ----------- >>
    private TextField poids;

    // ----------- << attribute.annotations@AAAAAAGEtfZd3P37NpY= >>
    // ----------- >>
    private Button enregistrer;

    // ----------- << attribute.annotations@AAAAAAGEtfZgU/4BBBY= >>
    // ----------- >>
    private Button annuler;

    private Label getImmatLabel() {
        return immatLabel;
    }

    private TextField getImmat() {
        return immat;
    }

    private Label getPoidsLabel() {
        return poidsLabel;
    }

    private TextField getPoids() {
        return poids;
    }

    private Button getEnregistrer() {
        return enregistrer;
    }

    private Button getAnnuler() {
        return annuler;
    }

    private void setImmatLabel(Label immatLabel) {
        this.immatLabel = immatLabel;
    }

    private void setImmat(TextField immat) {
        this.immat = immat;
    }

    private void setPoidsLabel(Label poidsLabel) {
        this.poidsLabel = poidsLabel;
    }

    private void setPoids(TextField poids) {
        this.poids = poids;
    }

    private void setEnregistrer(Button enregistrer) {
        this.enregistrer = enregistrer;
    }

    private void setAnnuler(Button annuler) {
        this.annuler = annuler;
    }

// ----------- << class.extras@AAAAAAGEtfVLk/2f09A= >>
// ----------- >>
}