/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.view;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEtfNfYf1Hl5Q= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEtfNfYf1Hl5Q= >>
// ----------- >>
public class VehiculesView {
    // ----------- << attribute.annotations@AAAAAAGEtfO9lP1x/pU= >>
    // ----------- >>
    private MenuBar menu;

    // ----------- << attribute.annotations@AAAAAAGEtfPdQv148S0= >>
    // ----------- >>
    private ListView listeVehicules;

    // ----------- << attribute.annotations@AAAAAAGEtfPfdP1+mEU= >>
    // ----------- >>
    private Button ajouterVehicule;

    // ----------- << attribute.annotations@AAAAAAGEtfPg+/2ErpE= >>
    // ----------- >>
    private Button supprimerVehicule;

    // ----------- << attribute.annotations@AAAAAAGEtfPimP2KxoA= >>
    // ----------- >>
    private Button editerVehicule;

    private MenuBar getMenu() {
        return menu;
    }

    private ListView getListeVehicules() {
        return listeVehicules;
    }

    private Button getAjouterVehicule() {
        return ajouterVehicule;
    }

    private Button getSupprimerVehicule() {
        return supprimerVehicule;
    }

    private Button getEditerVehicule() {
        return editerVehicule;
    }

    private void setMenu(MenuBar menu) {
        this.menu = menu;
    }

    private void setListeVehicules(ListView listeVehicules) {
        this.listeVehicules = listeVehicules;
    }

    private void setAjouterVehicule(Button ajouterVehicule) {
        this.ajouterVehicule = ajouterVehicule;
    }

    private void setSupprimerVehicule(Button supprimerVehicule) {
        this.supprimerVehicule = supprimerVehicule;
    }

    private void setEditerVehicule(Button editerVehicule) {
        this.editerVehicule = editerVehicule;
    }

// ----------- << class.extras@AAAAAAGEtfNfYf1Hl5Q= >>
// ----------- >>
}