/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */

package root.data;

import java.sql.Connection;
import java.util.ArrayList;

// ----------- << imports@AAAAAAGEq0cXHNRwSs0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEq0cXHNRwSs0= >>
// ----------- >>

/**
 * This class is used to access the Admin table.
 *
 * @param <Model> Model utilisé pour la table
 * @param <IdType> Type de l'identifiant de la table
 */
public class AdminDao<Model, IdType> extends Dao<Model, IdType> {
  /**
   * Constructeur.
   *
   * @param connexion Connexion à la base de données
   */
  public AdminDao(Connection connexion) {
    super(connexion);
  }

  /**
   * Insertion d'un nouvel enregistrement dans la table.
   *
   * @param model Modèle à insérer
   */

  @Override
  // ----------- << method.annotations@AAAAAAGEqwsK/vvtcX0= >>
  // ----------- >>
  public boolean insert(Model model) {
    // ----------- << method.body@AAAAAAGEqwsK/vvtcX0= >>
    // ----------- >>
    return false;
  }

  /**
   * Récupération d'un enregistrement de la table.
   *
   * @param id Identifiant de l'enregistrement à récupérer
   */

  @Override
  // ----------- << method.annotations@AAAAAAGEqxPR7/3rnfY= >>
  // ----------- >>
  public Model get(IdType id) {
    // ----------- << method.body@AAAAAAGEqxPR7/3rnfY= >>
    // ----------- >>
    return null;
  }

  @Override
  // ----------- << method.annotations@AAAAAAGEqwsRWPv5vW8= >>
  // ----------- >>
  public ArrayList<Model> getAll() {
    // ----------- << method.body@AAAAAAGEqwsRWPv5vW8= >>
    // ----------- >>
    return null;
  }
  /**
   * Mise à jour d'un enregistrement de la table.
   *
   * @param model Modèle à mettre à jour
   */

  @Override
  // ----------- << method.annotations@AAAAAAGEqwsStvv//Eo= >>
  // ----------- >>
  public boolean update(Model model) {
    // ----------- << method.body@AAAAAAGEqwsStvv//Eo= >>
    // ----------- >>
    return false;
  }
  /**
   * Suppression d'un enregistrement de la table.
   *
   * @param model Modèle à supprimer
   */

  @Override
  // ----------- << method.annotations@AAAAAAGEqw1CdPwvL+Y= >>
  // ----------- >>
  public boolean delete(Model model) {
    // ----------- << method.body@AAAAAAGEqw1CdPwvL+Y= >>
    // ----------- >>
    return false;
  }
  // ----------- << class.extras@AAAAAAGEq0cXHNRwSs0= >>
  // ----------- >>
}