/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.data;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEq15KwNjntgw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEq15KwNjntgw= >>
// ----------- >>
public class SingleConnection {
    // ----------- << attribute.annotations@AAAAAAGEq16nadkT/p8= >>
    // ----------- >>
    private static Connection connexion;

    // ----------- << method.annotations@AAAAAAGEq2AXxNksPnQ= >>
    // ----------- >>
    private SingleConnection() {
    // ----------- << method.body@AAAAAAGEq2AXxNksPnQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEszylo/RWLfA= >>
    // ----------- >>
    public static Connection getInstance() {
    // ----------- << method.body@AAAAAAGEszylo/RWLfA= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEq15KwNjntgw= >>
// ----------- >>
}