/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package root.data;

import java.util.*;
// ----------- << imports@AAAAAAGEqwbBWvs36Cc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEqwbBWvs36Cc= >>
// ----------- >>
public class VehiculeDAO<Model, IdType> extends DAO {
    /**
     * @param connexion
     */
    public VehiculeDAO(Connection connexion) {
        super(connexion);
    }

    /**
    * @param model
    */

    @Override
    // ----------- << method.annotations@AAAAAAGEqwsK/vvtcX0= >>
    // ----------- >>
    public boolean insert(Object model) {
    // ----------- << method.body@AAAAAAGEqwsK/vvtcX0= >>
    // ----------- >>
        return false;
    }
    /**
    * @param id
    */

    @Override
    // ----------- << method.annotations@AAAAAAGEqxPR7/3rnfY= >>
    // ----------- >>
    public Model get(Object id) {
    // ----------- << method.body@AAAAAAGEqxPR7/3rnfY= >>
    // ----------- >>
        return null;
    }

    /**
     * @param o
     */
    @Override
    public boolean insert(Object o) {
        return false;
    }

    /**
     * @param id
     */
    @Override
    public Object get(Object id) {
        return null;
    }

    @Override
    // ----------- << method.annotations@AAAAAAGEqwsRWPv5vW8= >>
    // ----------- >>
    public ArrayList<Model> getAll() {
    // ----------- << method.body@AAAAAAGEqwsRWPv5vW8= >>
    // ----------- >>
        return null;
    }

    /**
     * @param o
     */
    public boolean update(Model o) {
        return false;
    }

    /**
     * @param o
     */
    public boolean delete(Model o) {
        return false;
    }

    /**
    * @param model
    */
// ----------- << class.extras@AAAAAAGEqwbBWvs36Cc= >>
// ----------- >>
}